language: sh
sudo: required
git:
  depth: 1
  submodules: false
services:
- docker
#addons:
#  ssh_known_hosts: 51.15.187.88
before_script:
- docker run --rm --volume $TRAVIS_BUILD_DIR:/app composer:latest bash -c "composer require symfony/filesystem symfony/finder"
script:
- docker run --rm -v $TRAVIS_BUILD_DIR:/app -w /app php:7.3-rc-cli-alpine sh -c "php ci/build.php"
before_deploy:
- openssl aes-256-cbc -K $encrypted_a7673f68a3e8_key -iv $encrypted_a7673f68a3e8_iv -in ci/deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script:
      ssh lewebpedagogique@51.15.187.88 mkdir -p /srv/http/skyflow/data /srv/http/skyflow/composes &&
      rsync -r --delete-after $TRAVIS_BUILD_DIR/composes.json lewebpedagogique@51.15.187.88:/srv/http/skyflow/data/composes.json &&
      rsync -avz $TRAVIS_BUILD_DIR/public $TRAVIS_BUILD_DIR/templates lewebpedagogique@51.15.187.88:/srv/http/skyflow/composes
    on:
      branch: master
#  - provider: script
#    skip_cleanup: true
#    script: rsync -r --quiet $TRAVIS_BUILD_DIR/public lewebpedagogique@51.15.187.88:/srv/http/skyflow/composes && rsync -r --quiet $TRAVIS_BUILD_DIR/templates lewebpedagogique@51.15.187.88:/srv/http/skyflow/composes
#    on:
#      branch: master
#      rsync -r $TRAVIS_BUILD_DIR/public lewebpedagogique@51.15.187.88:/srv/http/skyflow/composes &&
