FROM node:alpine
LABEL maintainer="Skyflow - Franck DIOMANDE <fkdiomande@gmail.com>"
WORKDIR /graphql
RUN npm init -y
RUN yarn add express express-graphql graphql cors lodash vhost
RUN yarn global add nodemon
EXPOSE 80
CMD ["nodemon", "server.js"]